apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    project: roboshop
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      app: frontend
  template:
    metadata:
      labels:
        project: roboshop
        app: frontend
    spec:
      containers:
        - name: frontend
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/frontend
          envFrom:
            - configMapRef:
                name: frontend
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            livenessProbe:
              httpGet:
                path: /health
                port: 80
              initialDelaySeconds: 5
              periodSeconds: 5



---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  labels:
    project: roboshop
    app: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      app: cart
  template:
    metadata:
      labels:
        project: roboshop
        app: cart
    spec:
      containers:
        - name: cart
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/cart
          envFrom:
            - configMapRef:
                name: cart
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            livenessProbe:
              httpGet:
                path: /health
                port: 8080
              initialDelaySeconds: 5
              periodSeconds: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    project: roboshop
    app: catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      app: catalogue
  template:
    metadata:
      labels:
        project: roboshop
        app: catalogue
    spec:
      containers:
        - name: catalogue
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/catalogue
          envFrom:
            - configMapRef:
                name: catalogue
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            livenessProbe:
              httpGet:
                path: /health
                port: 8080
              initialDelaySeconds: 5
              periodSeconds: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    project: roboshop
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      app: user
  template:
    metadata:
      labels:
        project: roboshop
        app: user
    spec:
      containers:
        - name: user
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/user
          envFrom:
            - configMapRef:
                name: user
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            livenessProbe:
              httpGet:
                path: /health
                port: 8080
              initialDelaySeconds: 5
              periodSeconds: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  labels:
    project: roboshop
    app: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      app: shipping
  template:
    metadata:
      labels:
        project: roboshop
        app: shipping
    spec:
      containers:
        - name: shipping
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/shipping
          envFrom:
            - configMapRef:
                name: shipping
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            livenessProbe:
              httpGet:
                path: /health
                port: 8080
              initialDelaySeconds: 5
              periodSeconds: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    project: roboshop
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      app: payment
  template:
    metadata:
      labels:
        project: roboshop
        app: payment
    spec:
      containers:
        - name: payment
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/payment
          envFrom:
            - configMapRef:
                name: payment
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            livenessProbe:
              httpGet:
                path: /health
                port: 8080
              initialDelaySeconds: 5
              periodSeconds: 5
---
apiVersion: batch/v1
kind: Job
metadata:
  name: catalogue-schema
spec:
  template:
    spec:
      containers:
        - name: schema
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
          env:
            - name: SCHEMA_FILE
              value: db/master-data.js
          envFrom:
            - configMapRef:
                name: catalogue
      restartPolicy: Never
  backoffLimit: 0
---
apiVersion: batch/v1
kind: Job
metadata:
  name: shipping-app-user
spec:
  template:
    spec:
      containers:
        - name: app-user
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
          env:
            - name: SCHEMA_FILE
              value: db/app-user.sql
          envFrom:
            - configMapRef:
                name: shipping
      restartPolicy: Never
  backoffLimit: 0
---
apiVersion: batch/v1
kind: Job
metadata:
  name: shipping-master-data
spec:
  template:
    spec:
      containers:
        - name: master-data
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
          env:
            - name: SCHEMA_FILE
              value: db/master-data.sql
          envFrom:
            - configMapRef:
                name: shipping
      restartPolicy: Never
  backoffLimit: 0
---
apiVersion: batch/v1
kind: Job
metadata:
  name: shipping-schema
spec:
  template:
    spec:
      containers:
        - name: schema
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
          env:
            - name: SCHEMA_FILE
              value: db/schema.sql
          envFrom:
            - configMapRef:
                name: shipping
      restartPolicy: Never
  backoffLimit: 0